DOCS.md, README.md, main.go, plugin.go, vendor/github.com/joho/godotenv/autoload/autoload.go
Also fix #21 
* Fix load ENV from the config file.
* Support password flag.
* update documents.
cc @tboerger @bradrydzewski @Bugagazavr
=> Support password flag

DOCS.md
ref: https://github.com/drone/drone-plugin-index/commit/e2a87606a8fdb144781aad0ab666381b5c3368da
cc @bradrydzewski @tboerger
=> remove secret section

main.go, plugin.go, plugin_test.go
=> feat: Support import private key from file path.

plugin.go
=> docs: remove duplicated of port config.

easyssh/easyssh.go, main.go, plugin.go, plugin_test.go
=> feat: add easyssh and go routine.

DOCS.md
=> docs: [ci skip] add drone document.

DOCS.md, README.md, main.go, plugin.go, plugin_test.go
fix #44 
Same with [drone-scp](https://github.com/appleboy/drone-scp) plugin
=> feat: support username flag.

DOCS.md
=> docs: improve docs #48

main.go, plugin.go, plugin_test.go, vendor/github.com/appleboy/easyssh-proxy/easyssh.go, vendor/vendor.json
=> feat: Support proxy command.

main.go, plugin.go, plugin_test.go, vendor/github.com/appleboy/easyssh-proxy/Makefile, vendor/github.com/appleboy/easyssh-proxy/README.md, vendor/github.com/appleboy/easyssh-proxy/easyssh.go, vendor/vendor.json
=> refactor: upgrade easyssh to support DefaultConfig

vendor/github.com/appleboy/easyssh-proxy/Makefile, vendor/github.com/appleboy/easyssh-proxy/README.md, vendor/github.com/appleboy/easyssh-proxy/easyssh.go, vendor/golang.org/x/crypto/ssh/certs.go, vendor/golang.org/x/crypto/ssh/client.go, vendor/golang.org/x/crypto/ssh/client_auth.go, vendor/golang.org/x/crypto/ssh/common.go, vendor/golang.org/x/crypto/ssh/doc.go, vendor/golang.org/x/crypto/ssh/handshake.go, vendor/golang.org/x/crypto/ssh/keys.go, vendor/golang.org/x/crypto/ssh/server.go, vendor/golang.org/x/crypto/ssh/streamlocal.go, vendor/golang.org/x/crypto/ssh/tcpip.go, vendor/vendor.json
fix #67 
related issue: https://github.com/appleboy/easyssh-proxy/issues/16
=> refactor: HostKeyCallback is the function type used for verifying server

plugin.go, plugin_test.go
=> refactor: show errors if set password and key at the same time

.drone.yml
=> feat: support group build

plugin_test.go, vendor/github.com/appleboy/easyssh-proxy/easyssh.go, vendor/vendor.json
=> fix: get exit code from ssh run command.

plugin.go, plugin_test.go
=> Support stream output logs.

plugin.go
ref: https://github.com/appleboy/drone-ssh/issues/64#issuecomment-300415147
=> hide domain if only single host in config.

plugin.go, vendor/github.com/appleboy/easyssh-proxy/README.md, vendor/github.com/appleboy/easyssh-proxy/easyssh.go, vendor/vendor.json
=> upgrade easyssh to 1.1.6

main.go, plugin.go, plugin_test.go
fixed https://github.com/appleboy/drone-ssh/pull/90 #89
=> feat(env): pass secret to remote server.

main.go, plugin.go, plugin_test.go
=> add debug mode.

main.go, plugin.go, plugin_test.go
fix https://github.com/appleboy/drone-ssh/issues/86
=> Add sync mode.

.drone.yml, .gitignore, Dockerfile, Makefile
=> add arm arm64 and amd64 build.

.drone.yml
=> update drone-docker plugin.

main.go, plugin.go, vendor/github.com/appleboy/easyssh-proxy/README.md, vendor/github.com/appleboy/easyssh-proxy/easyssh.go, vendor/vendor.json
=> feat: upgrade easyssh-proxy and update flag of timeout field

main.go, plugin.go, vendor/github.com/appleboy/easyssh-proxy/README.md, vendor/github.com/appleboy/easyssh-proxy/easyssh.go, vendor/vendor.json
Reverts appleboy/drone-ssh#127
=> Revert "feat: upgrade easyssh-proxy and update flag of timeout field"

plugin.go, plugin_test.go
ref https://github.com/appleboy/ssh-action/issues/10
=> chore: support split from string text

go.mod, go.sum, main.go, plugin.go, plugin_test.go
related issue: https://github.com/appleboy/ssh-action/issues/56
=> chore: support UseInsecureCipher

plugin.go, plugin_test.go
https://github.com/appleboy/ssh-action/issues/75
=> chore: support Multiline SSH commands interpreted as single lines

plugin.go, plugin_test.go
=> chore: support multiple port

plugin.go
=> remove empty string output

main.go
fix https://github.com/appleboy/drone-ssh/issues/177
fix #60 #102 #173
Signed-off-by: Bo-Yi.Wu <appleboy.tw@gmail.com>
=> chore(scripts): disable SliceFlagSeparator

main.go
Reverts appleboy/drone-ssh#212
=> Revert "chore(scripts): disable SliceFlagSeparator"

DOCS.md, README.md
=> Document configuration through dotenv variables

plugin.go, plugin_test.go
ref: https://github.com/appleboy/ssh-action/issues/178
=> chore(auth): allow use password and key at same time

DOCS.md
=> fix: example with secrets

docker/Dockerfile
- Add `tzdata` package to the Dockerfile
fix #273
=> build: improve system compatibility and performance

main.go
- Add `FilePath` attribute with value `.host` to the configuration in `main` function
fix #270
=> feat: refactor configuration handling in main function

plugin.go
My OCD just kicks in :)) This has bothered me for a long time. Will also update README in https://github.com/appleboy/ssh-action to reflect this change.
UPDATE: README in `ssh-action` repo updated by [ssh-action#340](https://github.com/appleboy/ssh-action/pull/340)
=> fix: typo in success message
